import type { CSSProperties } from "react";

/** Co-located styles for the agent's Skills tab. */
export const s = {
  wrap: { maxWidth: 860 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    width: 220,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "8px 0 18px",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  row: (linked: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 8,
    borderRadius: 8,
    border: "1px solid " + (linked ? "var(--border-strong)" : "var(--border)"),
    background: linked ? "var(--bg-hover)" : "var(--bg-elevated)",
  }),
  handle: (linked: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: linked ? "grab" : "default",
    opacity: linked ? 1 : 0.35,
    display: "inline-flex",
  }),
  name: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  position: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  orderBtn: (disabled: boolean): CSSProperties => ({
    display: "inline-grid",
    placeItems: "center",
    width: 24,
    height: 24,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: disabled ? "var(--text-muted)" : "var(--text-secondary)",
    opacity: disabled ? 0.4 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
    padding: 0,
  }),
} as const;
