import type { CSSProperties } from "react";

/** Co-located styles for the import drawer. */
export const s = {
  body: { padding: "18px 22px 8px", display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  h3: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  notice: {
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 6,
    padding: "8px 10px",
  } satisfies CSSProperties,
  trust: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-secondary)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  error: {
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  fileInput: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  chips: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  catalogRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  catalogHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 4 } satisfies CSSProperties,
  catalogName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  catalogMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  previewHead: { display: "flex", alignItems: "center", gap: 8, marginTop: 4 } satisfies CSSProperties,
  previewLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  pre: {
    maxHeight: 280,
    overflow: "auto",
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  fileList: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 13,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
