import type { CSSProperties } from "react";

export const s = {
  panel: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  head: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
    padding: "16px 16px 12px",
  } satisfies CSSProperties,
  caption: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  roots: { marginTop: -6, fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  scroll: { flex: 1, minHeight: 0, overflow: "auto", padding: "0 8px 8px" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  row: (selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    borderRadius: 7,
    border: "none",
    textAlign: "left",
    background: selected ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
  }),
  rowIcon: (selected: boolean): CSSProperties => ({
    flexShrink: 0,
    color: selected ? "var(--accent-text)" : "var(--text-muted)",
  }),
  rowPath: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowBadge: { flexShrink: 0 } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 8, padding: "4px 8px" } satisfies CSSProperties,
  noMatch: { margin: 0, padding: "12px 10px", fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    padding: "10px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
} as const;
