import type { CSSProperties } from "react";
import type { ConventionCandidate } from "@devdigest/shared";

/** Co-located styles for CandidateCard. */
const STATUS_ACCENT: Record<ConventionCandidate["status"], string> = {
  pending: "var(--border-strong)",
  accepted: "var(--ok)",
  rejected: "var(--text-muted)",
};

export const s = {
  card: (status: ConventionCandidate["status"]): CSSProperties => ({
    display: "flex",
    gap: 18,
    padding: "16px 18px",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${STATUS_ACCENT[status]}`,
    opacity: status === "rejected" ? 0.6 : 1,
  }),
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  rule: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  rationale: {
    margin: 0,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  rationaleLabel: { fontWeight: 600, color: "var(--text-muted)" } satisfies CSSProperties,
  editRow: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  editControls: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" } satisfies CSSProperties,
  evidenceBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-base)",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderBottom: "1px solid var(--border)",
    fontSize: 12.5,
  } satisfies CSSProperties,
  evidenceLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-secondary)",
    textDecoration: "none",
    flex: 1,
  } satisfies CSSProperties,
  evidencePlain: { color: "var(--text-muted)", flex: 1 } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 12px",
    fontSize: 12.5,
    lineHeight: 1.55,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  confidenceRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 12.5 } satisfies CSSProperties,
  confidenceLabel: { color: "var(--text-muted)" } satisfies CSSProperties,
  bar: {
    display: "inline-block",
    width: 140,
    height: 5,
    borderRadius: 3,
    background: "var(--bg-hover)",
    overflow: "hidden",
  } satisfies CSSProperties,
  barFill: (pct: number, color: string): CSSProperties => ({
    display: "block",
    width: `${pct}%`,
    height: "100%",
    background: color,
  }),
  pct: { color: "var(--text-secondary)" } satisfies CSSProperties,
  skillBadge: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 132,
  } satisfies CSSProperties,
} as const;
