#!/usr/bin/env bash
# Shared by the agent guards (implementer-guard, readonly-guard, write-scope-guard).
# The caller sets GUARD_NAME and GUARD_HINT, then sources this file.
#
# Every guard: exit 0 = allow, exit 2 = block (stderr is fed back to the agent).
# The hook payload is read with jq when it is installed, otherwise with node (Node >= 22 is a
# project requirement), so the guards do not depend on anything a developer may lack.

ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
[[ -n "$ROOT" && -d "$ROOT" ]] || exit 0
ROOT="$(cd "$ROOT" && pwd -P)"

block() {
  {
    echo "BLOCKED by ${GUARD_NAME:-agent-guard}: $1"
    echo "Why: $2"
    echo "Do not work around this. ${GUARD_HINT:-Report it as a blocker.}"
  } >&2
  exit 2
}

# Splitting on shell operators is deliberately naive: a quoted `; git commit` inside an
# argument also becomes a segment, which errs towards blocking, never towards allowing.
segments() {
  sed -E 's/(&&|\|\||;|\||\(|\)|`|\$\()/\n/g' <<<"$1"
}

normalize() {
  local s="$1" prev=""
  while [[ "$s" != "$prev" ]]; do
    prev="$s"
    s="$(sed -E 's/^[[:space:]]+//; s/^(env|sudo|command|time|nohup|exec)[[:space:]]+//; s/^[A-Za-z_][A-Za-z0-9_]*=[^[:space:]]*[[:space:]]+//' <<<"$s")"
  done
  printf '%s' "$s"
}

GIT='^git([[:space:]]+-[Cc][[:space:]]+[^[:space:]]+)*[[:space:]]+'

lib_check_git_segment() {
  local s="$1"
  if grep -Eq "${GIT}(commit|push|pull|merge|rebase|reset|checkout|switch|stash|restore|clean|revert|cherry-pick|tag|am)([[:space:]]|$)" <<<"$s"; then
    block "$s" "git history and the working-tree state belong to the user; agents leave their changes uncommitted."
  fi
  if grep -Eq "${GIT}branch([[:space:]]+[^[:space:]]+)*[[:space:]]+(-[dDmMcCf]|--delete|--move|--copy|--force)([[:space:]]|$)" <<<"$s"; then
    block "$s" "branches are created and deleted by the user."
  fi
  if grep -Eq '^gh[[:space:]]+pr[[:space:]]+(create|ready|merge|close|reopen|edit|comment|review)([[:space:]]|$)' <<<"$s"; then
    block "$s" "a PR is opened by the user after the reviews and pr-self-review, not by an agent."
  fi
  return 0
}

lib_check_db_segment() {
  local s="$1"
  if grep -Eq '^(pnpm|npm|yarn)[[:space:]].*db:(migrate|seed)([[:space:]]|$)' <<<"$s" \
    || grep -Eq '^((npx|pnpm[[:space:]]+(exec|dlx))[[:space:]]+)?drizzle-kit[[:space:]]+(migrate|push|drop|up)([[:space:]]|$)' <<<"$s" \
    || grep -Eq '^((npx|pnpm[[:space:]]+exec)[[:space:]]+)?tsx[[:space:]]+([^[:space:]]*/)?src/db/(migrate|seed)' <<<"$s"; then
    block "$s" "writes to the local dev DB go through a dry run on a restored copy (INSIGHTS.md § What Works). Generate migrations with \`pnpm db:generate\`; integration tests migrate their own testcontainers DB."
  fi
  if grep -Eq '^((docker[[:space:]]+exec[[:space:]].*[[:space:]])?)(dropdb|pg_restore)([[:space:]]|$)' <<<"$s"; then
    block "$s" "the dev DB holds every imported repo and every local review."
  fi
  if grep -Eq '^docker([[:space:]]+compose|-compose)[[:space:]].*down.*[[:space:]](-v|--volumes)([[:space:]]|$)' <<<"$s" \
    || grep -Eq '^docker[[:space:]]+(volume[[:space:]]+(rm|prune)|system[[:space:]]+prune)([[:space:]]|$)' <<<"$s"; then
    block "$s" "never remove the Postgres volume (AGENTS.md § Gotchas)."
  fi
  return 0
}

lib_check_psql() {
  local cmd="$1"
  if grep -Eq '(^|[[:space:]"'"'"'])psql([[:space:]]|$)' <<<"$cmd" \
    && grep -Eiq '(insert[[:space:]]+into|update[[:space:]]+[a-z_"]+[[:space:]]+set|delete[[:space:]]+from|drop[[:space:]]+(table|database|schema|index)|alter[[:space:]]+table|truncate[[:space:]]|create[[:space:]]+(table|database|index))' <<<"$cmd"; then
    block "psql with a write statement" "writes to the local dev DB go through a dry run on a restored copy (INSIGHTS.md § What Works)."
  fi
  return 0
}

# Prints the repo-relative path; blocks a path outside the repository.
lib_repo_rel() {
  local p="$1" abs
  [[ "$p" = /* ]] && abs="$p" || abs="$ROOT/$p"
  abs="$(realpath -m "$abs" 2>/dev/null || printf '%s' "$abs")"
  case "$abs" in
    "$ROOT"/*) printf '%s' "${abs#"$ROOT"/}" ;;
    *) block "$p" "agents only edit files inside the repository." ;;
  esac
}

lib_check_protected_path() {
  local rel="$1"
  if grep -Eq '(^|/)(pnpm-lock\.yaml|package-lock\.json)$' <<<"$rel"; then
    block "$rel" "lockfiles are never hand-edited; change the dependency through that package's package manager."
  fi
  [[ "$rel" == "server/package.json" ]] \
    && block "$rel" "skip-worktree: the local copy diverges from the committed one (AGENTS.md § Do not touch)."
  [[ "$rel" == server/src/db/migrations/* ]] \
    && block "$rel" "migrations are generated by \`pnpm db:generate\`; an applied file is never edited — write a new migration."
  [[ "$rel" == server/clones/* ]] \
    && block "$rel" "runtime data: checkouts of imported repos."
  if grep -Eq '^\.claude/(agents/(scripts/|implementer\.md$|README\.md$)|settings(\.local)?\.json$)' <<<"$rel"; then
    block "$rel" "the guards, the implementer's own definition, the agents map and hook settings are changed by the user, not by an agent."
  fi
  if grep -Eq '(^|/)\.env(\.[^/]*)?$' <<<"$rel" && ! grep -Eq '\.example$' <<<"$rel"; then
    block "$rel" "local environment and secrets; document a new variable in .env.example instead."
  fi
  return 0
}

# Command text with quoted literals replaced by Q, so `grep -E 'a|b'` is not split on `|` and
# `awk '$1 > 2'` is not read as a redirect. A real quote scanner, not a regex: `"it's"` must not
# pair with a later `'`. Double-quoted strings holding `$(` or a backtick are kept verbatim, so
# `"$(rm x)"` is still seen; an unterminated quote keeps the rest of the text as it is.
lib_strip_quotes() {
  awk 'BEGIN { RS = "\001" } {
    s = $0; out = ""; q = ""; buf = ""; n = length(s)
    for (i = 1; i <= n; i++) {
      c = substr(s, i, 1)
      if (q == "") {
        if (c == "\047") { q = c; buf = "" }
        else if (c == "\"") { q = c; buf = "" }
        else if (c == "\\") { out = out c substr(s, i + 1, 1); i++ }
        else out = out c
      } else if (q == "\047") {
        if (c == "\047") { out = out "Q"; q = "" } else buf = buf c
      } else {
        if (c == "\\") { buf = buf c substr(s, i + 1, 1); i++ }
        else if (c == "\"") {
          if (index(buf, "$(") || index(buf, "`")) out = out "\"" buf "\""; else out = out "Q"
          q = ""
        } else buf = buf c
      }
    }
    if (q != "") out = out q buf
    printf "%s", out
  }' <<<"$1"
}

# True when the command writes through a shell redirect to anything but /dev/null or a fd.
lib_has_file_redirect() {
  local s
  s="$(lib_strip_quotes "$1" | sed -E 's/[0-9]*>>?[[:space:]]*(\/dev\/null|&[0-9-])//g; s/<<<?//g')"
  grep -q '>' <<<"$s"
}

PAYLOAD=""

# Prints a string field of the hook payload, e.g. `lib_payload_field tool_input.command`.
lib_payload_field() {
  if command -v jq >/dev/null 2>&1; then
    jq -r ".$1 // empty" <<<"$PAYLOAD" 2>/dev/null
  elif command -v node >/dev/null 2>&1; then
    node -e '
      let d = "";
      process.stdin.on("data", (c) => (d += c)).on("end", () => {
        let v;
        try { v = JSON.parse(d); } catch { return; }
        for (const k of process.argv[1].split(".")) v = v == null ? v : v[k];
        if (typeof v === "string") process.stdout.write(v);
      });' "$1" <<<"$PAYLOAD"
  fi
}

# Dispatches the three modes every guard supports. The caller defines check_command,
# check_path and check_tool (the last one receives the tool name).
lib_main() {
  case "${1:-}" in
    --check)      check_command "${2:-}"; exit 0 ;;
    --check-path) check_path "${2:-}"; exit 0 ;;
    --check-tool) check_tool "${2:-}"; exit 0 ;;
  esac

  command -v jq >/dev/null 2>&1 || command -v node >/dev/null 2>&1 \
    || block "every tool call" "neither jq nor node is available, so the hook payload cannot be read and the guard fails closed."
  PAYLOAD="$(cat)"
  local tool
  tool="$(lib_payload_field tool_name)" || exit 2
  case "$tool" in
    Bash) check_command "$(lib_payload_field tool_input.command)" ;;
    Edit|Write|MultiEdit)
      check_tool "$tool"
      check_path "$(lib_payload_field tool_input.file_path)" ;;
    NotebookEdit)
      check_tool "$tool"
      check_path "$(lib_payload_field tool_input.notebook_path)" ;;
  esac
  exit 0
}
