import type { CSSProperties } from "react";

/** Co-located styles for the attachment editor and its rows. */
export const s = {
  filterRow: { display: "flex", justifyContent: "flex-end", marginBottom: 14 } satisfies CSSProperties,
  filter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    width: 220,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  notice: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  row: (attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 8,
    borderRadius: 8,
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
  }),
  handle: (attached: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: attached ? "grab" : "default",
    opacity: attached ? 1 : 0.35,
    display: "inline-flex",
  }),
  checkbox: { width: 15, height: 15, margin: 0, accentColor: "var(--accent)" } satisfies CSSProperties,
  checkboxGap: { width: 15, height: 15, flexShrink: 0 } satisfies CSSProperties,
  path: { flex: 1, minWidth: 0, display: "flex" } satisfies CSSProperties,
  trailing: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  via: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  missing: { fontSize: 12, fontWeight: 600, color: "var(--warn)" } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    display: "inline-grid",
    placeItems: "center",
    width: 24,
    height: 24,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: disabled ? "var(--text-muted)" : "var(--text-secondary)",
    opacity: disabled ? 0.4 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
    padding: 0,
  }),
} as const;
